---
format: gfm
---

```{r}
#| label: setup
#| eval: true
#| include: false

# Specify project renv reqs
box::use(
	rmarkdown,
	markdown,
	mime,
	yaml
)
```


<!-- README.md is generated from README.qmd. Please edit that file. -->

# Zane's Website

This repository contains the source code for https://wzbillings.com/.

## "Acknowledgements"

* I stole a lot of code from [Andrew Heiss](https://andrewheiss.com) and [Andreas Handel](https://andreashandel.com). Thanks to both of them!

## Licensing

* All original code in my blog posts is licensed under the [GNU Affero General Public License](https://www.gnu.org/licenses/agpl-3.0.en.html). 

* All text and images created by me are licensed under the [CC BY-NC-SA 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/). If you want to use any materials for commercial purposes, please get in touch with me directly.

* Of course anything not created by me is subject to the original licensing terms.

## TODO

- [x] convert presentations to qmd
- [ ] finish CIs blog post
- [ ] convert projects to qmd
- [ ] update projects
- [x] add CV
- [x] Add CIVICs 2022 presentation (trajectories)
- [x] convert iframes to object tags for presentations
- [x] Fix presentation dates
- [ ] move papers blog to be hidden
