# Uses

This is a list of everything I use that I could think of to list here. If I forgot anything, feel free to let me know.

## Hardware

I actually have three hardware setups. It's kind of annoying and a big reason that I use Git for everything (but more on that later).

* In my **office** I use a Dell-prebuilt Precision 5820 with Windows 10 Enterprise. The processor is an Intel Core i9-10980XE 3.00 GHz; 64Gb RAM; AMD Radeon Pro WX 2100 processor.
* In my **house** I use a Dell prebuilt that I'll have to fill in the details for eventually cause I never remember.
* **On the go** I use a 2017 12" macbook with the retina screen. It's super lightweight and I liked that a lot while carrying it everywhere in undergrad, but now I find it very underwhelming for the price point and probably will never buy another Mac.
* My **phone** is a Samsung Galaxy A50. I leave it on do-not-disturb so if you aren't my parents or sister it is unlikely that I will see your texts or calls in a reasonable amount of time.

## Coding
* I almost exclusively use `R` these days.
* Sometimes I use `Stan`. Most of what I do can be facilitated with the `R` packages `rethinking` or `brms` but I've been moving more towards using my own `Stan` code recently.
* My preferred IDE for everything is `RStudio`. I use the "Vibrant Ink" theme that comes packaged with the IDE.
* In the past I've used Python (with atom) and MATLAB/Octave (with the GUI), but not so much anymore.
* On Windows, I exclusively use git bash as my terminal. On MacOS, I use the default terminal but set the language to bash.
* I use [Anonymous Pro](https://fonts.google.com/specimen/Anonymous+Pro) as my preferred coding font.

## Workflow / writing
* I use Git and GitHub for nearly everything. Almost all of my new projects (even small things) start by creating an R project with a git repo.
* Speaking of R projects, I use a `.rproj` file to organize anything I will do that will involve any amount of R code.
* For almost all of my research-related writing, I use R Markdown, which is an implementation of pandoc-flavored markdown that can integrate code and the results from running code.
* I've recently started using [Quarto](https://quarto.pub)
* For course projects that require me to use SAS or don't involve coding, I use LaTeX. I use [MiKTeX](https://miktex.org/) for my distribution and [TeXStudio](https://www.texstudio.org/) for my editor. Although I'm considering just using TinyTex and overleaf since I rarely use LaTeX standalone anymore.
* I use [Zotero](https://www.zotero.org/) for almost all of my reference management, although I've unfortunately been forced to use EndNote (which I will not provide a link to as I do not endorse it or Clarivate) recently.
* I use bibtex for all of my bibliographies as it works seamlessly with both pandoc and LaTeX.
* I use [WinCompose](http://wincompose.info/) for typing most special characters on Windows.
* I use google drive for anything non-code-related that I need to share. One day I'll consider switching to Quarto when collaborative editing is out, but that isn't today. If anyone knows a good markdown alternative, let me know.
* I've mostly switched to Quarto for all of my presentations. I still use Powerpoint occasionally (which I hate), but that's only because I dislike CSS fiddling more than manual fiddling. But Quarto presentations are so much easier than either the old R Markdown presentations or beamer, and they look way better.

## Other software
* In the past I've used Mathematica, but apparently Julia can do everything that Mathematica can do, so I don't recommend that anyone pay money for Mathematica.
* I'm also pretty good at SAS, but I will never buy a SAS license. Whenever I am forced to use SAS, I use SAS OnDemand for Academics. However, if you are a SAS user, I recommend pivoting away from SAS.
* I do not like using Microsoft Office. But I often find myself using Outlook and OneNote because figuring out anything else would take me time that I do not currently have.
* I use Firefox as my main browser, and I use google chrome when print to PDF in Firefox doesn't work. Chrome is also required for some `R`/`pandoc` procedures for turning HTML into PDF.
* This website is created with `quarto`, with source code on GitHub, and deployed by Netlify.
* I manage all my passwords with [BitWarden](https://bitwarden.com/).
* My time and project management skills are very bad. I use a system cobbled together from OneNote, Outlook's calendar, sticky notes in the office, and random scribblings on a notepad to manage what I need to get done. Usually it does not work very well, but I've never found a system that works better for me.
